# Generated by Django 4.2.3 on 2023-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2, verbose_name='年龄'),
        ),
    ]
